### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by lemaximedu66** [jonaskohl/CapsLockIndicator#141]
![image](https://user-images.githubusercontent.com/61986631/191539687-b2d83207-8f4e-4ea5-aa5f-f30a359b503b.png)

it's says that it is not supported anymore but i have the latest version...

**Comment by kiwichick888** [comment]
Yes, I get the same.

**Comment by kado897** [comment]
Me too for the last few days.

**Comment by jonbeebe** [comment]
same

**Comment by EverEve** [comment]
Same here

**Comment by jonaskohl** [comment]
Should be fixed now. Endoflife.date changed their format, which made my server-side script fail.

**Comment by lemaximedu66** [comment]
![image](https://user-images.githubusercontent.com/61986631/195700407-c65ff66f-774e-4906-9c6f-7663ab47f13b.png)
at least this is not the same message....

**Comment by kiwichick888** [comment]
Can confirm it is fixed for me. Thanks!!!

**Comment by lemaximedu66** [comment]
@jonaskohl i still have this weird message that i have posted a while ago

**Comment by jonaskohl** [comment]
@lemaximedu66 What OS and CapsLock Indicator version are you using?

**Comment by lemaximedu66** [comment]
windows 11 22H2 and the version i'm using is 3.16.1.2
